# Generated by Django 3.2.16 on 2023-01-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = []
